var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'application/json'});
  res.write(JSON.stringify(
    [
      {
        "_id": "640001038ce0f20b4c11021c",
        "index": 0,
        "guid": "ac81b454-2405-416b-a06d-7d5db3d17541",
        "isActive": true,
        "balance": "$2,303.82",
        "picture": "http://placehold.it/32x32",
        "age": 23,
        "eyeColor": "brown",
        "name": "Jeannette Hudson",
        "gender": "female",
        "company": "MANTRIX",
        "email": "jeannettehudson@mantrix.com",
        "phone": "+1 (832) 540-3923",
        "address": "757 Durland Place, Walton, Federated States Of Micronesia, 5227",
        "about": "Qui Lorem amet commodo Lorem ut duis reprehenderit. Ullamco tempor aute non reprehenderit nulla labore qui Lorem duis adipisicing. Laboris mollit et veniam ut est reprehenderit eiusmod ipsum ut aliquip est reprehenderit. Officia mollit pariatur cupidatat consectetur irure occaecat sit sunt incididunt non incididunt quis exercitation. Minim consectetur officia excepteur occaecat reprehenderit aliqua.\r\n",
        "registered": "2016-11-24T06:01:16 -06:-30",
        "latitude": 33.545229,
        "longitude": 75.971673,
        "tags": [
          "veniam",
          "nisi",
          "fugiat",
          "ullamco",
          "ex",
          "in",
          "proident"
        ]
      },
      {
        "_id": "64000103f909a0d9f9b4cb9b",
        "index": 1,
        "guid": "c5c50db7-1472-43ae-9408-bfd98ad33e7c",
        "isActive": true,
        "balance": "$2,486.99",
        "picture": "http://placehold.it/32x32",
        "age": 22,
        "eyeColor": "brown",
        "name": "Christensen Doyle",
        "gender": "male",
        "company": "ENTROPIX",
        "email": "christensendoyle@entropix.com",
        "phone": "+1 (829) 527-2479",
        "address": "449 Waldane Court, Verdi, Kentucky, 2534",
        "about": "Excepteur est incididunt deserunt excepteur reprehenderit. Culpa eu magna esse mollit minim. Consequat sunt commodo duis reprehenderit aute mollit amet amet nisi exercitation tempor cillum. Esse est veniam labore nisi. Ipsum aliquip ullamco amet eiusmod. Nisi sint laboris cillum in.\r\n",
        "registered": "2016-03-13T07:21:05 -06:-30",
        "latitude": 89.974557,
        "longitude": -110.694555,
        "tags": [
          "dolore",
          "incididunt",
          "nostrud",
          "amet",
          "et",
          "eu",
          "amet"
        ]
      },
      {
        "_id": "6400010327e11cc9fbe8be3d",
        "index": 2,
        "guid": "69db601f-433c-4a33-a1b9-e386eb389ae4",
        "isActive": false,
        "balance": "$3,006.73",
        "picture": "http://placehold.it/32x32",
        "age": 29,
        "eyeColor": "blue",
        "name": "Cook Fleming",
        "gender": "male",
        "company": "EPLODE",
        "email": "cookfleming@eplode.com",
        "phone": "+1 (853) 532-2106",
        "address": "904 Village Road, Norwood, Rhode Island, 9844",
        "about": "Lorem ex laboris veniam do incididunt pariatur esse aliqua duis non enim ullamco. Sint pariatur ullamco est occaecat cillum ea. Ad culpa ut non pariatur non aute sint officia in. Eiusmod enim consequat elit consectetur magna in nisi. Nulla duis incididunt laborum laboris adipisicing. Voluptate do irure est sint labore veniam commodo amet dolor. Qui sunt fugiat tempor labore.\r\n",
        "registered": "2017-06-24T03:48:05 -06:-30",
        "latitude": 71.265201,
        "longitude": -56.319317,
        "tags": [
          "incididunt",
          "nisi",
          "commodo",
          "nisi",
          "exercitation",
          "laborum",
          "nostrud"
        ]
      },
      {
        "_id": "6400010306c451d9394f80c4",
        "index": 3,
        "guid": "5a3669b6-63d2-41b7-9ccd-0203a38afc8c",
        "isActive": false,
        "balance": "$3,480.12",
        "picture": "http://placehold.it/32x32",
        "age": 32,
        "eyeColor": "green",
        "name": "Hall Foster",
        "gender": "male",
        "company": "XTH",
        "email": "hallfoster@xth.com",
        "phone": "+1 (864) 560-2595",
        "address": "728 Narrows Avenue, Whitehaven, Nebraska, 9372",
        "about": "Quis ullamco sint id ullamco duis laboris minim Lorem est cillum qui. Nulla aliquip mollit ipsum et in reprehenderit commodo exercitation aliqua quis mollit. Ipsum eu velit cupidatat duis voluptate et laborum aliqua laboris duis nisi non dolor.\r\n",
        "registered": "2016-06-18T11:45:46 -06:-30",
        "latitude": 14.631312,
        "longitude": -70.718582,
        "tags": [
          "proident",
          "mollit",
          "voluptate",
          "exercitation",
          "laborum",
          "laborum",
          "ipsum"
        ]
      },
      {
        "_id": "6400010396005a2ad7972156",
        "index": 4,
        "guid": "0963228a-be50-42ff-9c98-63019af51596",
        "isActive": true,
        "balance": "$2,071.34",
        "picture": "http://placehold.it/32x32",
        "age": 23,
        "eyeColor": "green",
        "name": "Holly Rowe",
        "gender": "female",
        "company": "DYMI",
        "email": "hollyrowe@dymi.com",
        "phone": "+1 (994) 541-3835",
        "address": "434 Wilson Street, Interlochen, Washington, 573",
        "about": "Mollit Lorem aliqua do deserunt proident id eiusmod incididunt ea laboris incididunt ex reprehenderit non. Nisi ea laboris officia ea consectetur occaecat id. Sint incididunt laborum nulla ad dolor enim.\r\n",
        "registered": "2014-12-23T04:50:08 -06:-30",
        "latitude": 7.23005,
        "longitude": -28.777572,
        "tags": [
          "commodo",
          "sit",
          "Lorem",
          "tempor",
          "mollit",
          "irure",
          "est"
        ]
      },
      {
        "_id": "64000103a9bba3d33c6e011a",
        "index": 5,
        "guid": "75c1a71e-a292-4e00-9cd0-f9c83dec652b",
        "isActive": true,
        "balance": "$2,352.66",
        "picture": "http://placehold.it/32x32",
        "age": 31,
        "eyeColor": "green",
        "name": "Emily Gallagher",
        "gender": "female",
        "company": "STOCKPOST",
        "email": "emilygallagher@stockpost.com",
        "phone": "+1 (878) 512-2597",
        "address": "665 Cyrus Avenue, Heil, Kansas, 5290",
        "about": "Cupidatat eiusmod adipisicing minim exercitation in et sint culpa. Amet magna consequat proident pariatur ex sit id veniam consectetur ullamco labore ad irure. Quis in minim magna esse amet ex. Consectetur ut id veniam nisi anim aliquip ipsum excepteur pariatur esse duis sunt adipisicing ipsum. Sunt non laborum qui occaecat sint. Duis proident sit ea aliqua pariatur veniam ipsum ullamco sunt.\r\n",
        "registered": "2019-03-28T05:41:51 -06:-30",
        "latitude": 78.15246,
        "longitude": 28.532434,
        "tags": [
          "magna",
          "commodo",
          "ad",
          "culpa",
          "exercitation",
          "ut",
          "consectetur"
        ]
      },
      {
        "_id": "64000103c3ec46d8a3ce35f8",
        "index": 6,
        "guid": "d9fea382-c988-4229-9d86-d1ccae233f98",
        "isActive": false,
        "balance": "$3,591.34",
        "picture": "http://placehold.it/32x32",
        "age": 40,
        "eyeColor": "green",
        "name": "Sheri Randall",
        "gender": "female",
        "company": "APEXIA",
        "email": "sherirandall@apexia.com",
        "phone": "+1 (965) 418-3425",
        "address": "191 Sands Street, Jardine, Missouri, 1084",
        "about": "Lorem esse qui eiusmod officia amet. Labore sit ex ut id laboris dolore ad sint ex magna commodo dolore qui. Duis veniam do in tempor sunt non sit incididunt. Quis eu excepteur voluptate cillum sint voluptate magna do tempor Lorem do voluptate mollit eiusmod. Ut consectetur magna eu eu incididunt ipsum adipisicing elit Lorem nulla. Amet voluptate duis ipsum eiusmod eu nostrud pariatur aute sint Lorem amet deserunt dolor. Veniam consectetur ullamco sit commodo cupidatat aliquip qui velit sint eu.\r\n",
        "registered": "2014-12-02T12:57:20 -06:-30",
        "latitude": 6.617459,
        "longitude": 10.689272,
        "tags": [
          "dolor",
          "do",
          "exercitation",
          "veniam",
          "voluptate",
          "do",
          "ut"
        ]
      }
    ]
  ));
  res.end();
}).listen(8080);